### ISSUE TITLE
Binaries in git repo

### ISSUE THREAD

**Issue by NHOrus** [Loafter/WebTop#2]
As a person who once did that on his own go project - don't. They add overhead to repo and make it painful to clone after you did some rebuilds and commits. Nothing better to expand repo hundred-fold.

**Comment by pierrre** [comment]
You should use releases: https://github.com/Loafter/WebTop/releases

**Comment by pierrre** [comment]
And google `git remove file from history`.

**Comment by Loafter** [comment]
Ok. i try fix it
