### ISSUE TITLE
systemMonitorDispatcher.StartMeasure undefined (type *SystemMonitorDispatcher has no field or method StartMeasure)

### ISSUE THREAD

**Issue by ArviZ** [Loafter/WebTop#5]
arviz@v6111:~/projects/WebTop$ go env
GOARCH="amd64"
GOBIN="/usr/local/go/bin/"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/arviz/projects/WebTop/bin/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by ArviZ** [comment]
oh, sorry
./RequestSelector.go:32

**Comment by Loafter** [comment]
Change Startmeasure() to  StartMeasure() should fix this error
i commit this fix

**Comment by ArviZ** [comment]
Thanks!
