### ISSUE TITLE
The process has been killed in a minute

### ISSUE THREAD

**Issue by ArviZ** [Loafter/WebTop#6]
arviz@v6111:~$ ./WebTop
:3000
2015/01/13 13:04:58 info: can't messure cpu info for process sshd
2015/01/13 13:04:58 info: can't messure cpu info for process sshd
Killed

**Comment by ArviZ** [comment]
:3000
2015/01/13 13:12:49 info: can't messure cpu info for process sshd
2015/01/13 13:12:49 info: can't messure cpu info for process sshd
2015/01/13 13:18:00 info: can't messure cpu info for process sshd
2015/01/13 13:18:00 info: can't messure cpu info for process sshd
2015/01/13 13:19:37 info: can't messure cpu info for process sshd
2015/01/13 13:19:37 info: can't messure cpu info for process sshd
2015/01/13 13:22:12 info: can't messure cpu info for process sshd
2015/01/13 13:22:12 info: can't messure cpu info for process sshd
2015/01/13 13:22:13 info: can't messure cpu info for process sshd
2015/01/13 13:22:13 info: can't messure cpu info for process sshd
2015/01/13 13:23:03 info: can't messure cpu info for process sshd
2015/01/13 13:23:03 info: can't messure cpu info for process sshd
2015/01/13 13:24:43 info: can't messure cpu info for process sshd
2015/01/13 13:24:43 info: can't messure cpu info for process sshd
2015/01/13 13:25:26 info: sleep collect top info job
2015/01/13 13:25:28 info: start collect top info job
2015/01/13 13:25:36 info: can't messure cpu info for process sshd
2015/01/13 13:25:36 info: can't messure cpu info for process sshd
2015/01/13 13:25:58 info: can't messure cpu info for process sshd
2015/01/13 13:25:58 info: can't messure cpu info for process sshd
2015/01/13 13:26:38 info: can't messure cpu info for process sshd
2015/01/13 13:26:38 info: can't messure cpu info for process sshd
2015/01/13 13:27:07 info: can't messure cpu info for process sshd
2015/01/13 13:27:07 info: can't messure cpu info for process sshd
2015/01/13 13:27:09 info: can't messure cpu info for process sshd
2015/01/13 13:27:09 info: can't messure cpu info for process sshd
2015/01/13 13:27:10 info: can't messure cpu info for process sshd
2015/01/13 13:27:11 info: can't messure cpu info for process sshd
2015/01/13 13:27:39 info: can't messure cpu info for process sshd
2015/01/13 13:27:39 info: can't messure cpu info for process sshd
2015/01/13 13:27:42 info: can't messure cpu info for process sshd
2015/01/13 13:27:42 info: can't messure cpu info for process sshd
2015/01/13 13:28:17 info: can't messure cpu info for process sshd
2015/01/13 13:28:17 info: can't messure cpu info for process sshd
2015/01/13 13:28:25 info: problem with read stat file with pid 9417
2015/01/13 13:28:47 info: can't messure cpu info for process sshd
2015/01/13 13:28:47 info: can't messure cpu info for process sshd
2015/01/13 13:29:35 info: can't messure cpu info for process sshd
2015/01/13 13:29:35 info: can't messure cpu info for process sshd
2015/01/13 13:32:00 info: can't messure cpu info for process sshd
2015/01/13 13:32:00 info: can't messure cpu info for process sshd
2015/01/13 13:33:26 info: can't messure cpu info for process sshd
2015/01/13 13:33:26 info: can't messure cpu info for process sshd
2015/01/13 13:34:27 info: can't messure cpu info for process sshd
2015/01/13 13:34:27 info: can't messure cpu info for process sshd
2015/01/13 13:36:53 info: can't messure cpu info for process sshd
2015/01/13 13:36:53 info: can't messure cpu info for process sshd
2015/01/13 13:38:34 info: can't messure cpu info for process sshd
2015/01/13 13:38:34 info: can't messure cpu info for process sshd

**Comment by Loafter** [comment]
I don't think this is error.
This message appear then main measure process try compare 2 cpu sample and calculate cpu load for process.
Then some process created between 2 sample measure function can't measure the loading for this process.
I think this is many sshd process with many pids
try change log function for display pid 
log.Println(stErr, processItem.Name, processItem.Pid)
